export const courses = [
  {
    id: 1,
    title: "Mastering Generative AI: From Prompting to Production",
    price: 349,
    description:
      "Unlock the power of generative AI tools like ChatGPT, Midjourney, and DALL·E. This course dives deep into the architecture behind large language models and generative systems.",
    img: "https://pub-e93d5c9fdf134c89830082377f6df465.r2.dev/2024/06/Generative-AI-1024x512.png",
    instructor: "Dr. Emily Carter",
    duration: "6 Weeks (36 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Artificial Intelligence",
    rating: 4.7,
    students: 8243,
    includes: [
      "36 hours of video",
      "50+ hands-on exercises",
      "Quizzes & projects",
      "Certificate of completion",
    ],
  },
  {
    id: 2,
    title: "UI/UX Design Essentials",
    price: 150,
    description:
      "Master the fundamentals of user interface and experience design. This course covers the psychology behind design decisions, practical wireframing, prototyping in Figma, and accessibility principles. Whether you’re aiming for web or mobile.",
    img: "https://img.freepik.com/premium-photo/mobile-application-ui-ux-design-development-concept_999671-59792.jpg",
    instructor: "Jane Smith",
    duration: "4 Weeks (24 Hours)",
    level: "Beginner",
    language: "English",
    category: "Design",
    rating: 4.5,
    students: 5021,
    includes: [
      "24 hours of video",
      "15 case studies",
      "Figma files & assets",
      "Certificate of completion",
    ],
  },
  {
    id: 3,
    title: "Full-Stack Web Development Bootcamp",
    price: 499,
    description:
      "Become a full-stack developer by learning HTML, CSS, JavaScript, React, Node.js, and MongoDB. This bootcamp focuses on building robust applications with hands-on coding challenges.",
    img: "https://i.pinimg.com/originals/10/1e/a3/101ea302c96d44e3939ce330abe46056.jpg",
    instructor: "Alex Johnson",
    duration: "10 Weeks (60 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Web Development",
    rating: 4.8,
    students: 12754,
    includes: [
      "60 hours of video",
      "Real-world projects",
      "Code-alongs",
      "Certificate of completion",
    ],
  },
  {
    id: 4,
    title: "Python for Data Science and Machine Learning",
    price: 299,
    description:
      "Learn Python programming with a focus on data science and machine learning. This course includes step-by-step coding exercises, data visualization with matplotlib and seaborn, and machine learning with scikit-learn.",
    img: "https://railsware.com/blog/wp-content/uploads/2018/10/Python-for-Data-Science-illustration.jpg",
    instructor: "Sara Ahmed",
    duration: "8 Weeks (48 Hours)",
    level: "Beginner to Intermediate",
    language: "English",
    category: "Data Science",
    rating: 4.6,
    students: 9842,
    includes: [
      "48 hours of video",
      "10+ projects",
      "Downloadable notebooks",
      "Certificate of completion",
    ],
  },
  {
    id: 5,
    title: "Digital Marketing Mastery",
    price: 199,
    description:
      "Master the core pillars of digital marketing including SEO, social media, email campaigns, and content marketing. Learn to develop marketing strategies, analyze audience data.",
    img: "https://public-files.gumroad.com/variants/nzfnbxq30ww44z9oxn2b8q2vj29h/3298c3eb001bbed90f1d616da66708480096a0a1b6e81bd4f8a2d6e9b831d301",
    instructor: "Michael Lee",
    duration: "5 Weeks (30 Hours)",
    level: "Beginner",
    language: "English",
    category: "Marketing",
    rating: 4.4,
    students: 6113,
    includes: [
      "30 hours of video",
      "Live ad campaigns",
      "Marketing templates",
      "Certificate of completion",
    ],
  },
  {
    id: 6,
    title: "Cloud Computing with AWS",
    price: 379,
    description:
      "Get hands-on experience with Amazon Web Services (AWS) including EC2, S3, Lambda, and more. You’ll learn cloud architecture principles, deployment strategies.",
    img: "https://tse2.mm.bing.net/th/id/OIP.NBaQ6zPy_VdJhRywMaxaHwHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    instructor: "Rachel Kim",
    duration: "6 Weeks (36 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Cloud Computing",
    rating: 4.6,
    students: 7231,
    includes: [
      "36 hours of video",
      "Lab environments",
      "AWS certification prep",
      "Certificate of completion",
    ],
  },
  {
    id: 7,
    title: "Cybersecurity Fundamentals",
    price: 249,
    description:
      "Understand the principles of cybersecurity including network architecture, cryptography, threat analysis, and ethical hacking. The course combines theory with lab.",
    img: "https://itsecuritywire.com/uploads/2021/11/Making-Cybersecurity-Awareness-a-Priority-in-the-Aftermath-of-01.webp",
    instructor: "Ethan Brooks",
    duration: "7 Weeks (42 Hours)",
    level: "Beginner to Intermediate",
    language: "English",
    category: "Cybersecurity",
    rating: 4.5,
    students: 5892,
    includes: [
      "42 hours of video",
      "Interactive labs",
      "Capture-the-flag exercises",
      "Certificate of completion",
    ],
  },
  {
    id: 8,
    title: "Data Visualization with Tableau",
    price: 179,
    description:
      "Learn how to create compelling dashboards, charts, and stories using Tableau, connecting to multiple data sources, and building business.",
    img: "https://www.tableau.com/sites/default/files/2023-07/Data%20culture.png",
    instructor: "Nina Patel",
    duration: "3 Weeks (18 Hours)",
    level: "Beginner",
    language: "English",
    category: "Data Visualization",
    rating: 4.3,
    students: 4127,
    includes: [
      "18 hours of video",
      "Real datasets",
      "Portfolio-ready projects",
      "Certificate of completion",
    ],
  },
  {
    id: 9,
    title: "Agile Project Management with Scrum",
    price: 199,
    description:
      "Master agile methodologies including Scrum, Kanban, and user story management. This course provides a complete guide to running sprints and applying Scrum frameworks in real corporate environments.",
    img: "https://academy.visiplus.com/blog/wp-content/uploads/2017/08/Fotolia_94657673_Subscription_Monthly_M.jpg",
    instructor: "Carlos Ramirez",
    duration: "4 Weeks (20 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Project Management",
    rating: 4.4,
    students: 4375,
    includes: [
      "20 hours of video",
      "Scrum templates",
      "Team management tools",
      "Certificate of completion",
    ],
  },
  {
    id: 10,
    title: "Intro to Blockchain and Web3",
    price: 329,
    description:
      "Understand the blockchain ecosystem in-depth including Bitcoin, Ethereum, smart contracts, and NFTs. Learn how to write smart contracts with Solidity and deploy decentralized apps (dApps) using popular Web3 tools.",
    img: "https://www.kai.or.id/wp-content/uploads/2022/02/blockchain.jpeg",
    instructor: "Priya Mehta",
    duration: "6 Weeks (36 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Blockchain",
    rating: 4.6,
    students: 6541,
    includes: [
      "36 hours of video",
      "Smart contract labs",
      "NFT minting exercises",
      "Certificate of completion",
    ],
  },
  {
    id: 11,
    title: "Full-Stack Web Development with MERN",
    price: 399,
    description:
      "Build modern, scalable web applications using MongoDB, Express, React, and Node.js. From setting up your dev environment to deploying live applications, this course covers it in a project-based learning format.",
    img: "https://itechnasik.com/wp-content/uploads/2023/11/Mern-Stack-Developer.png",
    instructor: "Samuel Johnson",
    duration: "8 Weeks (48 Hours)",
    level: "Intermediate",
    language: "English",
    category: "Web Development",
    rating: 4.8,
    students: 10452,
    includes: [
      "48 hours of video",
      "Complete real-world project",
      "Backend and frontend development",
      "Certificate of completion",
    ],
  }
];
